// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetPokemonByIdData,
  GetPokemonByIdErrors,
  GetPokemonByIdResponses,
  ListPokemonData,
  ListPokemonResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List all pokemon (optionally filtered by type)
 */
export const listPokemon = <ThrowOnError extends boolean = false>(
  options?: Options<ListPokemonData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListPokemonResponses, unknown, ThrowOnError>({
    url: "/pokemon",
    ...options,
  });

/**
 * Get a pokemon by id
 */
export const getPokemonById = <ThrowOnError extends boolean = false>(
  options: Options<GetPokemonByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetPokemonByIdResponses,
    GetPokemonByIdErrors,
    ThrowOnError
  >({ url: "/pokemon/{id}", ...options });
