// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8787" | (string & {});
};

export type PokemonList = Array<Pokemon>;

export type Pokemon = {
  id: string;
  name: string;
  types: Array<PokemonType>;
  /**
   * In decimeters
   */
  height: number;
  /**
   * In hectograms
   */
  weight: number;
  sprite: string;
};

export type PokemonType =
  | "normal"
  | "fire"
  | "water"
  | "electric"
  | "grass"
  | "ice"
  | "fighting"
  | "poison"
  | "ground"
  | "flying"
  | "psychic"
  | "bug"
  | "rock"
  | "ghost"
  | "dragon"
  | "dark"
  | "steel"
  | "fairy";

export type ListPokemonData = {
  body?: never;
  path?: never;
  query?: {
    type?: PokemonType & unknown;
  };
  url: "/pokemon";
};

export type ListPokemonResponses = {
  /**
   * List of pokemon
   */
  200: PokemonList;
};

export type ListPokemonResponse =
  ListPokemonResponses[keyof ListPokemonResponses];

export type GetPokemonByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/pokemon/{id}";
};

export type GetPokemonByIdErrors = {
  /**
   * Pokemon not found
   */
  404: unknown;
};

export type GetPokemonByIdResponses = {
  /**
   * A pokemon
   */
  200: Pokemon;
};

export type GetPokemonByIdResponse =
  GetPokemonByIdResponses[keyof GetPokemonByIdResponses];
