// Shared types used by the components in `src/components/`.
// In Part 3 of the workshop, these get replaced by the types
// generated by @hey-api/openapi-ts — same shape, codegen-backed.

export type PokemonType =
  | 'normal'
  | 'fire'
  | 'water'
  | 'electric'
  | 'grass'
  | 'ice'
  | 'fighting'
  | 'poison'
  | 'ground'
  | 'flying'
  | 'psychic'
  | 'bug'
  | 'rock'
  | 'ghost'
  | 'dragon'
  | 'dark'
  | 'steel'
  | 'fairy'

export type Pokemon = {
  id: string
  name: string
  types: PokemonType[]
  height: number
  weight: number
  sprite: string
}
